# Generated by Django 4.2.6 on 2023-10-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0002_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dental',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Известные ', 'verbose_name_plural': 'Известные '},
        ),
    ]
